apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-app-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "arch.homework"
    http:
      paths:
        - path: /otusapp/mipastukhov(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: health-app-service 
              port: 
                number: 80